#ifndef _PEANO_APPLICATIONS_PEANOCLAW_RECORDS_DATA_H
#define _PEANO_APPLICATIONS_PEANOCLAW_RECORDS_DATA_H

#ifdef Parallel
	#include <mpi.h>
#endif
#include "tarch/logging/Log.h"
#include "tarch/la/Vector.h"
#include <bitset>
#include <string>
#include <iostream>

namespace peanoclaw {
 namespace records {
    class Data;
    class DataPacked;
 }
}

/**
 * @author This class was autogenerated by DaStGen
 * 		   DataStructureGenerator (DaStGen), 2007-2009,
 * 		   by Wolfgang Eckhardt
 *
 * 		   build date: 09-12-2010 17:47
 *
 * @date   03/02/2013 21:06
 */
class peanoclaw::records::Data { 
   
   public:
      
      typedef peanoclaw::records::DataPacked Packed;
      
      struct PersistentRecords {
         double _u;
         /**
          * Generated
          */
         PersistentRecords();
         
         /**
          * Generated
          */
         PersistentRecords(const double& u);
         
         /**
          * Generated
          */
         double getU() const;
         
         /**
          * Generated
          */
         void setU(const double& u);
         
         
      };
      
   private: 
      PersistentRecords _persistentRecords;
      
   public:
      /**
       * Generated
       */
      Data();
      
      /**
       * Generated
       */
      Data(const PersistentRecords& persistentRecords);
      
      /**
       * Generated
       */
      Data(const double& u);
      
      /**
       * Generated
       */
//      virtual ~Data();
      
      /**
       * Generated
       */
      double getU() const {
        return _persistentRecords._u;
      }
      
      /**
       * Generated
       */
      void setU(const double& u) {
        _persistentRecords._u = u;
      }
      
      /**
       * Generated
       */
      std::string toString() const;
      
      /**
       * Generated
       */
      void toString(std::ostream& out) const;
      
      
      PersistentRecords getPersistentRecords() const;
      /**
       * Generated
       */
      DataPacked convert() const;
      
      protected:
         static tarch::logging::Log _log;

#if 0  
    #ifdef Parallel
        
         int _senderRank;
         
      public:
         
         /**
          * Global that represents the mpi datatype.
          */
         static MPI_Datatype Datatype;
         
         /**
          * Initializes the data type for the mpi operations. Has to be called
          * before the very first send or receive operation is called.
          */
         static void initDatatype();
         
         static void shutdownDatatype();
         
         void send(int destination, int tag);
         
         void receive(int source, int tag);
         
         static bool isMessageInQueue(int tag);
         
         int getSenderRank() const;
         
   #endif
#endif
      
   };
   
   /**
    * @author This class was autogenerated by DaStGen
    * 		   DataStructureGenerator (DaStGen), 2007-2009,
    * 		   by Wolfgang Eckhardt
    *
    * 		   build date: 09-12-2010 17:47
    *
    * @date   03/02/2013 21:06
    */
   class peanoclaw::records::DataPacked { 
      
      public:
         
         struct PersistentRecords {
            double _u;
            /**
             * Generated
             */
            PersistentRecords();
            
            /**
             * Generated
             */
            PersistentRecords(const double& u);
            
            /**
             * Generated
             */
            double getU() const;
            
            /**
             * Generated
             */
            void setU(const double& u);
            
            
         };
         
      private: 
         PersistentRecords _persistentRecords;
         
      public:
         /**
          * Generated
          */
         DataPacked();
         
         /**
          * Generated
          */
         DataPacked(const PersistentRecords& persistentRecords);
         
         /**
          * Generated
          */
         DataPacked(const double& u);
         
         /**
          * Generated
          */
         virtual ~DataPacked();
         
         /**
          * Generated
          */
         double getU() const;
         
         /**
          * Generated
          */
         void setU(const double& u);
         
         /**
          * Generated
          */
         std::string toString() const;
         
         /**
          * Generated
          */
         void toString(std::ostream& out) const;
         
         
         PersistentRecords getPersistentRecords() const;
         /**
          * Generated
          */
         Data convert() const;
         
         
      #ifdef Parallel
         protected:
            static tarch::logging::Log _log;
            
            int _senderRank;
            
         public:
            
            /**
             * Global that represents the mpi datatype.
             */
            static MPI_Datatype Datatype;
            
            /**
             * Initializes the data type for the mpi operations. Has to be called
             * before the very first send or receive operation is called.
             */
            static void initDatatype();
            
            static void shutdownDatatype();
            
            void send(int destination, int tag);
            
            void receive(int source, int tag);
            
            static bool isMessageInQueue(int tag);
            
            int getSenderRank() const;
            
      #endif
         
      };
      
      #endif
      
