# This is a makefile for Peano's PoissonWithJacobi component
# generated by the Peano Development Tools (PDT) 

# Include files
-include files.mk


# Set Paths
# ---------
# Please adopt these directories to your Peano installation. The values are 
# used by the compiler and linker calls.
PEANO_HOME   = ../../src
PROJECT_HOME = ..   # project home is the directory holding your project-specific subdirectory


# Set Dimension
# -------------
DIM=-DDim2
#DIM=-DDim3
#DIM=-DDim4


# Configure Peano
#----------------
PROJECT_CLFAGS = -DDebug -DAsserts 
PROJECT_LFLAGS = 
EXECUTABLE=peanoclaw-debug
#EXECUTABLE=peano-PoissonWithJacobi-debug


# Configure System
# ----------------
# These values are used to assemble the symbols SYSTEM_CFLAGS and SYSTEM_LFLAGS.
INCLUDE_TBB=$(TBB_INC)
#INCLUDE_OMP=$(OMP_INC)
INCLUDE_OMP=-fopenmp
INCLUDE_MPI=$(MPI_INC)


LINK_TBB=$(TBB_SHLIB)
#LINK_OMP=$(OMP_SHLIB)
LINK_OMP=-fopenmp
#LINK_MPI=-lpthread -lrt -lmpich
LINK_MPI=


# Assemble Compiler Flags
# -----------------------
SYSTEM_CFLAGS = $(INCLUDE_TBB) $(INCLUDE_MPI)
#SYSTEM_CFLAGS =  $(INCLUDE_OMP) $(INCLUDE_MPI)
SYSTEM_LFLAGS = $(LINK_TBB)    $(LINK_MPI)
#SYSTEM_LFLAGS =  $(LINK_OMP)    $(LINK_MPI)



# Settings for the GNU Compiler (Debug Mode)
# ------------------------------------------
CC=g++
COMPILER_CFLAGS=-O0 -pedantic -pedantic-errors -Wall -Werror -Wstrict-aliasing -fstrict-aliasing -ggdb
COMPILER_LFLAGS=


# Settings for the GNU Compiler (Release Mode)
# --------------------------------------------
#CC=g++
#CFLAGS=-O3 -fstrict-aliasing -fno-rtti -fno-exceptions
#LFLAGS=-


# Settings for the Intel Compiler (Debug Mode)
# --------------------------------------------
#CC=icpc
#CFLAGS=-O0 -fstrict-aliasing 
#LFLAGS=


# Settings for the Intel Compiler (Release Mode)
# ----------------------------------------------
#CC=icpc
#CFLAGS=-fast -fstrict-aliasing 
#LFLAGS=


# Settings for the XLC Compiler (Debug Mode)
# --------------------------------------------
#CC=xlcc
#CFLAGS=-O0 -fstrict-aliasing -qpack_semantic=gnu 
#LFLAGS=


# Settings for the XLC Compiler (Release Mode)
# ----------------------------------------------
#CC=xlcc
#CFLAGS=-fast -fstrict-aliasing -qpack_semantic=gnu 
#LFLAGS=-fast 
#EXECUTABLE=peano-PoissonWithJacobi-release


OBJECTS=$(SOURCES:.cpp=.o)



all: header build



files.mk:
	touch files.mk
	echo -n SOURCES= > files.mk
	find $(PEANO_HOME) -name '*.cpp' -printf '%p ' >> files.mk
	find $(PROJECT_HOME) -name '*.cpp' -printf '%p ' >> files.mk
	find $(PEANO_HOME) -name '*.cpp' -printf 'COMPILE %p TO %p OBJECT FILE\n' >> compiler-minutes.txt
	find $(PROJECT_HOME) -name '*.cpp' -printf 'COMPILE %p TO %p OBJECT FILE\n' >> compiler-minutes.txt
	echo -n '\n\nLINK ' >> compiler-minutes.txt
	find $(PEANO_HOME) -name '*.cpp' -printf '%p ' >> compiler-minutes.txt
	find $(PROJECT_HOME) -name '*.cpp' -printf '%p ' >> compiler-minutes.txt



header:
	@echo  --- This is Peano 3 ---


build: files.mk $(OBJECTS)
	$(CC) $(PROJECT_LFLAGS) $(COMPILER_LFLAGS) $(SYSTEM_LFLAGS) $(OBJECTS) -o $(EXECUTABLE)
	@echo
	@echo build of Peano with component PoissonWithJacobi successful
	@echo visit Peano\'s homepage at http://www.peano-framework.org


clean:
	rm -f $(EXECUTABLE)
	rm -f $(OBJECTS)
	rm -f files.mk
	rm -f compiler-minutes.txt


$(OBJECTS): %.o : %.cpp
	$(CC) $(DIM) $(PROJECT_CFLAGS) $(COMPILER_CFLAGS) $(SYSTEM_CFLAGS) -I$(PROJECT_HOME) -I$(PEANO_HOME) -c $< -o $@
