#ifndef _PEANO_APPLICATIONS_PEANOCLAW_RECORDS_VERTEXDESCRIPTION_H
#define _PEANO_APPLICATIONS_PEANOCLAW_RECORDS_VERTEXDESCRIPTION_H

#include "peano/utils/Globals.h"
#ifdef Parallel
	#include <mpi.h>
#endif
#include "tarch/logging/Log.h"
#include "tarch/la/Vector.h"
#include <bitset>
#include <string>
#include <iostream>

namespace peanoclaw {
 namespace records {
    class VertexDescription;
    class VertexDescriptionPacked;
 }
}

/**
 * @author This class was autogenerated by DaStGen
 * 		   DataStructureGenerator (DaStGen), 2007-2009,
 * 		   by Wolfgang Eckhardt
 *
 * 		   build date: 09-12-2010 17:47
 *
 * @date   03/02/2013 21:06
 */
class peanoclaw::records::VertexDescription { 
   
   public:
      
      typedef peanoclaw::records::VertexDescriptionPacked Packed;
      
      enum IterationParity {
         EVEN = 0, ODD = 1
      };
      
      struct PersistentRecords {
         tarch::la::Vector<TWO_POWER_D,int> _indicesOfAdjacentCellDescriptions;
         IterationParity _lastUpdateIterationParity;
         bool _touched;
         /**
          * Generated
          */
         PersistentRecords();
         
         /**
          * Generated
          */
         PersistentRecords(const tarch::la::Vector<TWO_POWER_D,int>& indicesOfAdjacentCellDescriptions, const IterationParity& lastUpdateIterationParity, const bool& touched);
         
         /**
          * Generated
          */
         tarch::la::Vector<TWO_POWER_D,int> getIndicesOfAdjacentCellDescriptions() const;
         
         /**
          * Generated
          */
         void setIndicesOfAdjacentCellDescriptions(const tarch::la::Vector<TWO_POWER_D,int>& indicesOfAdjacentCellDescriptions);
         
         /**
          * Generated
          */
         IterationParity getLastUpdateIterationParity() const;
         
         /**
          * Generated
          */
         void setLastUpdateIterationParity(const IterationParity& lastUpdateIterationParity);
         
         /**
          * Generated
          */
         bool getTouched() const;
         
         /**
          * Generated
          */
         void setTouched(const bool& touched);
         
         
      };
      
   private: 
      PersistentRecords _persistentRecords;
      
   public:
      /**
       * Generated
       */
      VertexDescription();
      
      /**
       * Generated
       */
      VertexDescription(const PersistentRecords& persistentRecords);
      
      /**
       * Generated
       */
      VertexDescription(const tarch::la::Vector<TWO_POWER_D,int>& indicesOfAdjacentCellDescriptions, const IterationParity& lastUpdateIterationParity, const bool& touched);
      
      /**
       * Generated
       */
      virtual ~VertexDescription();
      
      /**
       * Generated
       */
      tarch::la::Vector<TWO_POWER_D,int> getIndicesOfAdjacentCellDescriptions() const;
      
      /**
       * Generated
       */
      void setIndicesOfAdjacentCellDescriptions(const tarch::la::Vector<TWO_POWER_D,int>& indicesOfAdjacentCellDescriptions);
      
      /**
       * Generated
       */
      int getIndicesOfAdjacentCellDescriptions(int elementIndex) const;
      
      /**
       * Generated
       */
      void setIndicesOfAdjacentCellDescriptions(int elementIndex, const int& indicesOfAdjacentCellDescriptions);
      
      /**
       * Generated
       */
      IterationParity getLastUpdateIterationParity() const;
      
      /**
       * Generated
       */
      void setLastUpdateIterationParity(const IterationParity& lastUpdateIterationParity);
      
      /**
       * Generated
       */
      bool getTouched() const;
      
      /**
       * Generated
       */
      void setTouched(const bool& touched);
      
      /**
       * Generated
       */
      static std::string toString(const IterationParity& param);
      
      /**
       * Generated
       */
      static std::string getIterationParityMapping();
      
      /**
       * Generated
       */
      std::string toString() const;
      
      /**
       * Generated
       */
      void toString(std::ostream& out) const;
      
      
      PersistentRecords getPersistentRecords() const;
      /**
       * Generated
       */
      VertexDescriptionPacked convert() const;
      
      
   #ifdef Parallel
      protected:
         static tarch::logging::Log _log;
         
         int _senderRank;
         
      public:
         
         /**
          * Global that represents the mpi datatype.
          */
         static MPI_Datatype Datatype;
         
         /**
          * Initializes the data type for the mpi operations. Has to be called
          * before the very first send or receive operation is called.
          */
         static void initDatatype();
         
         static void shutdownDatatype();
         
         void send(int destination, int tag);
         
         void receive(int source, int tag);
         
         static bool isMessageInQueue(int tag);
         
         int getSenderRank() const;
         
   #endif
      
   };
   
   /**
    * @author This class was autogenerated by DaStGen
    * 		   DataStructureGenerator (DaStGen), 2007-2009,
    * 		   by Wolfgang Eckhardt
    *
    * 		   build date: 09-12-2010 17:47
    *
    * @date   03/02/2013 21:06
    */
   class peanoclaw::records::VertexDescriptionPacked { 
      
      public:
         
         typedef peanoclaw::records::VertexDescription::IterationParity IterationParity;
         
         struct PersistentRecords {
            tarch::la::Vector<TWO_POWER_D,int> _indicesOfAdjacentCellDescriptions;
            IterationParity _lastUpdateIterationParity;
            bool _touched;
            /**
             * Generated
             */
            PersistentRecords();
            
            /**
             * Generated
             */
            PersistentRecords(const tarch::la::Vector<TWO_POWER_D,int>& indicesOfAdjacentCellDescriptions, const IterationParity& lastUpdateIterationParity, const bool& touched);
            
            /**
             * Generated
             */
            tarch::la::Vector<TWO_POWER_D,int> getIndicesOfAdjacentCellDescriptions() const;
            
            /**
             * Generated
             */
            void setIndicesOfAdjacentCellDescriptions(const tarch::la::Vector<TWO_POWER_D,int>& indicesOfAdjacentCellDescriptions);
            
            /**
             * Generated
             */
            IterationParity getLastUpdateIterationParity() const;
            
            /**
             * Generated
             */
            void setLastUpdateIterationParity(const IterationParity& lastUpdateIterationParity);
            
            /**
             * Generated
             */
            bool getTouched() const;
            
            /**
             * Generated
             */
            void setTouched(const bool& touched);
            
            
         };
         
      private: 
         PersistentRecords _persistentRecords;
         
      public:
         /**
          * Generated
          */
         VertexDescriptionPacked();
         
         /**
          * Generated
          */
         VertexDescriptionPacked(const PersistentRecords& persistentRecords);
         
         /**
          * Generated
          */
         VertexDescriptionPacked(const tarch::la::Vector<TWO_POWER_D,int>& indicesOfAdjacentCellDescriptions, const IterationParity& lastUpdateIterationParity, const bool& touched);
         
         /**
          * Generated
          */
         virtual ~VertexDescriptionPacked();
         
         /**
          * Generated
          */
         tarch::la::Vector<TWO_POWER_D,int> getIndicesOfAdjacentCellDescriptions() const;
         
         /**
          * Generated
          */
         void setIndicesOfAdjacentCellDescriptions(const tarch::la::Vector<TWO_POWER_D,int>& indicesOfAdjacentCellDescriptions);
         
         /**
          * Generated
          */
         int getIndicesOfAdjacentCellDescriptions(int elementIndex) const;
         
         /**
          * Generated
          */
         void setIndicesOfAdjacentCellDescriptions(int elementIndex, const int& indicesOfAdjacentCellDescriptions);
         
         /**
          * Generated
          */
         IterationParity getLastUpdateIterationParity() const;
         
         /**
          * Generated
          */
         void setLastUpdateIterationParity(const IterationParity& lastUpdateIterationParity);
         
         /**
          * Generated
          */
         bool getTouched() const;
         
         /**
          * Generated
          */
         void setTouched(const bool& touched);
         
         /**
          * Generated
          */
         static std::string toString(const IterationParity& param);
         
         /**
          * Generated
          */
         static std::string getIterationParityMapping();
         
         /**
          * Generated
          */
         std::string toString() const;
         
         /**
          * Generated
          */
         void toString(std::ostream& out) const;
         
         
         PersistentRecords getPersistentRecords() const;
         /**
          * Generated
          */
         VertexDescription convert() const;
         
         
      #ifdef Parallel
         protected:
            static tarch::logging::Log _log;
            
            int _senderRank;
            
         public:
            
            /**
             * Global that represents the mpi datatype.
             */
            static MPI_Datatype Datatype;
            
            /**
             * Initializes the data type for the mpi operations. Has to be called
             * before the very first send or receive operation is called.
             */
            static void initDatatype();
            
            static void shutdownDatatype();
            
            void send(int destination, int tag);
            
            void receive(int source, int tag);
            
            static bool isMessageInQueue(int tag);
            
            int getSenderRank() const;
            
      #endif
         
      };
      
      #endif
      
